name: members-video
favicon: null
layout_spectrum: 0.3286983754951507
typography_spectrum: 0.29346541152335703
title: Members Video
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.12069785827770829
  lightness: 0.24804219091311097
  saturation: 0.04324986902065575
  rhythmicContrast: 0.7468973102513701
purpose: []
